# Generated by Django 4.2.3 on 2023-07-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('businessentityid', models.IntegerField(primary_key=True, serialize=False)),
                ('persontype', models.CharField(max_length=2)),
                ('namestyle', models.BooleanField()),
                ('title', models.CharField(max_length=8, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('middle', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=10, null=True)),
                ('emailpromotion', models.IntegerField()),
                ('modifieddate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('businessentityid', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalidnumber', models.CharField(max_length=15)),
                ('loginid', models.CharField(max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('maritalstatus', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('hiredate', models.DateField()),
                ('salariedflag', models.BooleanField()),
                ('vacationhours', models.IntegerField()),
                ('sickleavehours', models.IntegerField()),
                ('currentflag', models.BooleanField()),
                ('modifieddate', models.DateTimeField(auto_now=True)),
                ('organizationnode', models.CharField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.person')),
            ],
        ),
    ]
